version: 1.0.{build}
image: Visual Studio 2019
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
  - cinst opencover.portable
  - cinst codecov
before_build:
  # Display .NET Core version
  - cmd: dotnet --version  
  # Display minimal restore text
  - cmd: dotnet restore DotNetCleanTemplate.sln --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish DotNetCleanTemplate.sln
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  # restore packages for our unit tests
  #- cmd: dotnet restore ./tests/DotNetCleanTemplate.Tests/CleanTemplate.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  #- cmd: dotnet test
  - OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test" -output:CleanTemplate_coverage.xml -oldStyle -register:user
  - codecov -f "CleanTemplate_coverage.xml"
on_finish :
  # any cleanup in here
deploy: off